### ISSUE TITLE
gradle runData task failed

### ISSUE THREAD

**Issue by 1337Pixelmal** [RoyalAliceAcademyOfSciences/SimElectricity#19]
The mod itself can be built, but the resourse are missing. Whenever i try to generate resources, i got following output in log.
Build environment: Windows 10 x64, jdk 17.
> Task :runData
2024-04-29 16:57:03,238 main WARN Advanced terminal features are not available in this environment
[16:57:03] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgedatauserdev, --assetIndex, 1.18, --assetsDir, C:\Users\Antero\.gradle\caches\forge_gradle\assets, --gameDir, ., --fml.forgeVersion, 39.0.59, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, --mod, sime_essential, --all, --output, C:\Users\Antero\Desktop\sime\SimElectricity\src\generated\resources, --existing, C:\Users\Antero\Desktop\sime\SimElectricity\src\main\resources]
[16:57:03] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.10 by Oracle Corporation
[16:57:03] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Antero/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8.5/9d1c0c3a304ae6697ecd477218fa61b850bf57fc/mixin-0.8.5.jar%2327!/ Service=ModLauncher Env=CLIENT
Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [C:\Users\Antero\Desktop\sime\SimElectricity\librikka\build\..\bin\main]
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:74)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.moddiscovery.AbstractModLocator.createMod(AbstractModLocator.java:48)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.lambda$scanMods$6(MinecraftLocator.java:53)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:55)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:64)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:180)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:100)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [C:\Users\Antero\Desktop\sime\SimElectricity\librikka\build\..\bin\main]
        ... 35 more

> Task :runData FAILED

>FAILURE: Build failed with an exception.

>* What went wrong:
>Execution failed for task ':runData'.
> Process 'command 'C:\Program Files\Java\jdk-17\bin\java.exe'' finished with non-zero exit value 1

**Comment by AuroraRAS** [comment]
Thank you for your feedback.

Can you provide more information? 
Are you operating in an IDE? What steps can be taken to reproduce this error?

**Comment by 1337Pixelmal** [comment]
Well, i'm not using any IDE, just CMD. The steps is described in "Setup the Environment" (https://github.com/rikka0w0/SimElectricity?tab=readme-ov-file#setup-the-environment-) and "Build and Test" (https://github.com/rikka0w0/SimElectricity?tab=readme-ov-file#build-and-test-). Is there anything else, that i could provide? Oh, and, yeah, i will try to build this mod on linux environment

**Comment by 1337Pixelmal** [comment]
Sorry, closed issue on accident

**Comment by 1337Pixelmal** [comment]
Ok, i tried the same on linux.
Environment: java17-openjfx (installed with hope, that it will do the trick), jdk17-openjdk, kernel - 6.6.1-arch1-1, bash 5.2.15.
Build failed, got the following in output:
\> Task :runData
2024-04-30 18:29:30,246 main WARN Advanced terminal features are not available in this environment
[18:29:30] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgedatauserdev, --assetIndex, 1.18, --assetsDir, /home/antero/.gradle/caches/forge_gradle/assets, --gameDir, ., --fml.forgeVersion, 39.0.59, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, --mod, sime_essential, --all, --output, /home/antero/SimElectricity/src/generated/resources, --existing, /home/antero/SimElectricity/src/main/resources]
[18:29:30] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.11 by N/A
[18:29:30] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/antero/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8.5/9d1c0c3a304ae6697ecd477218fa61b850bf57fc/mixin-0.8.5.jar%2327!/ Service=ModLauncher Env=CLIENT
Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [/home/antero/SimElectricity/librikka/build/../bin/main]
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:74)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.moddiscovery.AbstractModLocator.createMod(AbstractModLocator.java:48)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.lambda$scanMods$6(MinecraftLocator.java:53)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:55)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:64)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:180)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.59/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:100)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [/home/antero/SimElectricity/librikka/build/../bin/main]
        ... 35 more

\> Task :runData FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runData'.
\> Process 'command '/usr/lib/jvm/java-17-openjdk/bin/java'' finished with non-zero exit value 1

* Try:
\> Run with --stacktrace option to get the stack trace.
\> Run with --info or --debug option to get more log output.
\> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
13 actionable tasks: 5 executed, 8 up-to-date

**Comment by AuroraRAS** [comment]
I think the problem might be the coordination between [LibRikka](https://github.com/rikka0w0/librikka/) and forge-1.18.1-39.0.59.

The LibRikka did not successfully generate its bin folder. If you trying to `cd SimElectricity/librikka/` and  `./gradlew runData`, you'll got that errors:

```
[11:42:37] [main/WARN]: Assets URL 'union:/root/.gradle/caches/forge_gradle/minecraft_user_repo/net/minecraftforge/forge/1.18.1-39.0.59_mapped_official_1.18.1/forge-1.18.1-39.0.59_mapped_official_1.18.1.jar%2377!/assets/.mcassetsroot' uses unexpected schema
[11:42:37] [main/WARN]: Assets URL 'union:/root/.gradle/caches/forge_gradle/minecraft_user_repo/net/minecraftforge/forge/1.18.1-39.0.59_mapped_official_1.18.1/forge-1.18.1-39.0.59_mapped_official_1.18.1.jar%2377!/data/.mcassetsroot' uses unexpected schema

```

**Comment by 1337Pixelmal** [comment]
So... what i have to do? I've tested, got the same result with librikka.
Maybe there already built librikka and SimElectricity for 1.18.1? Because i'm trying to build all of that just to play with SimElectricity

**Comment by AuroraRAS** [comment]
Maybe we need to wait for the LibRikka author to fix it. I haven't maintained this project in too long to be able to help more.

**Comment by 1337Pixelmal** [comment]
Okay, thanks for your assistance!

**Comment by rikka0w0** [comment]
Delete all `lazyToken 'source_roots', {` sections in `build.gradle` and try again, this should be sufficient to fix the issue. I forget why I added this. I use Eclipse as my IDE, and that's why you see the `../bin/main` path...

**Comment by 1337Pixelmal** [comment]
Ok, i've removed all that sections in build.gradle in root directory, but build is still failed. But this time i got a generated resources, then i built the mod and librikka, and it works... almost. There is chuncks missing in world, where i places any blocks from SE and rejoin the world. Converters (RF to SE and vice versa) not working at all.
With SE i installed only Immersive Engineering and FluxNetworks.
I also got some errors related to librikka in minecraft log, i've attached the log file.
There is log for runData:

>To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/7.3/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build
>
>\> Configure project :
WARNING: This project is configured to use the official obfuscation mappings provided by Mojang. These mapping fall under their associated license, you should be fully aware of this license. For the latest license text, refer below, or the reference copy here: https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md, You can hide this warning by running the `hideOfficialWarningUntilChanged` task
WARNING: (c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, but you may not redistribute the mappings complete and unmodified. Microsoft makes no warranties, express or implied, with respect to the mappings provided here.  Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End User License Agreement available at https://account.mojang.com/documents/minecraft_eula.
>
>\> Configure project :librikka
WARNING: This project is configured to use the official obfuscation mappings provided by Mojang. These mapping fall under their associated license, you should be fully aware of this license. For the latest license text, refer below, or the reference copy here: https://github.com/MinecraftForge/MCPConfig/blob/master/Mojang.md, You can hide this warning by running the `hideOfficialWarningUntilChanged` task
WARNING: (c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, but you may not redistribute the mappings complete and unmodified. Microsoft makes no warranties, express or implied, with respect to the mappings provided here.  Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End User License Agreement available at https://account.mojang.com/documents/minecraft_eula.
>
>\> Task :processResources
Substituting strings into mods.toml
>
>\> Task :runData
2024-05-01 01:59:46,135 main WARN Advanced terminal features are not available in this environment
[01:59:46] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgedatauserdev, --assetIndex, 1.18, --assetsDir, C:\Users\Antero\.gradle\caches\forge_gradle\assets, --gameDir, ., --fml.forgeVersion, 39.0.59, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, --mod, sime_essential, --all, --output, C:\Users\Antero\Desktop\sime\SimElectricity\src\generated\resources, --existing, C:\Users\Antero\Desktop\sime\SimElectricity\src\main\resources]
[01:59:46] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.10 by Oracle Corporation
[01:59:46] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Antero/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8.5/9d1c0c3a304ae6697ecd477218fa61b850bf57fc/mixin-0.8.5.jar%2327!/ Service=ModLauncher Env=CLIENT
[01:59:48] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgedatauserdev' with arguments [--gameDir, ., --assetsDir, C:\Users\Antero\.gradle\caches\forge_gradle\assets, --assetIndex, 1.18, --mod, sime_essential, --all, --output, C:\Users\Antero\Desktop\sime\SimElectricity\src\generated\resources, --existing, C:\Users\Antero\Desktop\sime\SimElectricity\src\main\resources]
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[01:59:48] [main/INFO]: Initializing Data Gatherer for mods [sime_essential]
[01:59:52] [modloading-worker-0/INFO]: Forge mod loading, version 39.0.59, for MC 1.18.1 with MCP 20211210.034407
[01:59:52] [modloading-worker-0/INFO]: MinecraftForge v39.0.59 Initialized
[01:59:52] [modloading-worker-0/ERROR]: Null comment for config option server, this is invalid and may be disallowed in the future.
[01:59:52] [main/WARN]: Assets URL 'union:/C:/Users/Antero/.gradle/caches/forge_gradle/minecraft_user_repo/net/minecraftforge/forge/1.18.1-39.0.59_mapped_official_1.18.1/forge-1.18.1-39.0.59_mapped_official_1.18.1.jar%2377!/assets/.mcassetsroot' uses unexpected schema
[01:59:52] [main/WARN]: Assets URL 'union:/C:/Users/Antero/.gradle/caches/forge_gradle/minecraft_user_repo/net/minecraftforge/forge/1.18.1-39.0.59_mapped_official_1.18.1/forge-1.18.1-39.0.59_mapped_official_1.18.1.jar%2377!/data/.mcassetsroot' uses unexpected schema
[01:59:53] [main/INFO]: Starting provider: Block States: sime_essential
[01:59:53] [main/INFO]: Block States: sime_essential finished after 605 ms
[01:59:53] [main/INFO]: All providers took: 605 ms
>
>The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=4feb4e91-0ed6-4c11-ae60-81249afcfb7c, currentDir=C:\Users\Antero\Desktop\sime\SimElectricity}
Attempting to read last messages from the daemon log...
Daemon pid: 2964
  log file: C:\Users\Antero\.gradle\daemon\7.3\daemon-2964.out.log
----- Last  20 lines from daemon log file - daemon-2964.out.log -----
WARNING: (c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, but you may not redistribute the mappings complete and unmodified. Microsoft makes no warranties, express or implied, with respect to the mappings provided here.  Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End User License Agreement available at https://account.mojang.com/documents/minecraft_eula.
Substituting strings into mods.toml
2024-05-01 01:59:46,135 main WARN Advanced terminal features are not available in this environment
[01:59:46] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgedatauserdev, --assetIndex, 1.18, --assetsDir, C:\Users\Antero\.gradle\caches\forge_gradle\assets, --gameDir, ., --fml.forgeVersion, 39.0.59, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, --mod, sime_essential, --all, --output, C:\Users\Antero\Desktop\sime\SimElectricity\src\generated\resources, --existing, C:\Users\Antero\Desktop\sime\SimElectricity\src\main\resources]
[01:59:46] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.10 by Oracle Corporation
[01:59:46] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Antero/.gradle/caches/modules-2/files-2.1/org.spongepowered/mixin/0.8.5/9d1c0c3a304ae6697ecd477218fa61b850bf57fc/mixin-0.8.5.jar%2327!/ Service=ModLauncher Env=CLIENT
[01:59:48] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgedatauserdev' with arguments [--gameDir, ., --assetsDir, C:\Users\Antero\.gradle\caches\forge_gradle\assets, --assetIndex, 1.18, --mod, sime_essential, --all, --output, C:\Users\Antero\Desktop\sime\SimElectricity\src\generated\resources, --existing, C:\Users\Antero\Desktop\sime\SimElectricity\src\main\resources]
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
[01:59:48] [main/INFO]: Initializing Data Gatherer for mods [sime_essential]
[01:59:52] [modloading-worker-0/INFO]: Forge mod loading, version 39.0.59, for MC 1.18.1 with MCP 20211210.034407
[01:59:52] [modloading-worker-0/INFO]: MinecraftForge v39.0.59 Initialized
[01:59:52] [modloading-worker-0/ERROR]: Null comment for config option server, this is invalid and may be disallowed in the future.
[01:59:52] [main/WARN]: Assets URL 'union:/C:/Users/Antero/.gradle/caches/forge_gradle/minecraft_user_repo/net/minecraftforge/forge/1.18.1-39.0.59_mapped_official_1.18.1/forge-1.18.1-39.0.59_mapped_official_1.18.1.jar%2377!/assets/.mcassetsroot' uses unexpected schema
[01:59:52] [main/WARN]: Assets URL 'union:/C:/Users/Antero/.gradle/caches/forge_gradle/minecraft_user_repo/net/minecraftforge/forge/1.18.1-39.0.59_mapped_official_1.18.1/forge-1.18.1-39.0.59_mapped_official_1.18.1.jar%2377!/data/.mcassetsroot' uses unexpected schema
[01:59:53] [main/INFO]: Starting provider: Block States: sime_essential
[01:59:53] [main/INFO]: Block States: sime_essential finished after 605 ms
[01:59:53] [main/INFO]: All providers took: 605 ms
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
----- End of the daemon log -----
>
>
>FAILURE: Build failed with an exception.
>
>\* What went wrong:
Could not dispatch a message to the daemon.
>
>\* Try:
>\> Run with --stacktrace option to get the stack trace.
>\> Run with --info or --debug option to get more log output.
>\> Run with --scan to get full insights.
>
>\* Get more help at https://help.gradle.org

Screenshot with missing chunk:
![2024-05-01_02 27 31](https://github.com/rikka0w0/SimElectricity/assets/148631286/0d68cd54-404a-4a28-999e-dd74fff69685)

[latest.log](https://github.com/rikka0w0/SimElectricity/files/15170152/latest.log)

**Comment by rikka0w0** [comment]
> [01:59:53] [main/INFO]: All providers took: 605 ms

If you see this, it means resource generation works, just ignore the following message:
> [01:59:53] [main/INFO]: All providers took: 605 ms
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.
----- End of the daemon log -----

The missing chunk suggests that the map is corrupted, can you reproduce the problem in the development environment(launch with `./gradlew runClient`)?

**Comment by 1337Pixelmal** [comment]
The world was created after istallation of mods in the new profile. The world became corrupted after i placed blocks from SE.
The problem reproduced in development environment with gradlew runClient. Still world becomes corrupted after placing blocks from SE. 
Update: i made a few tests. They are shows, that the corruption is related to the thee-phase cable joint, and it's connection with some poles, or cross-arm (10kv). After that, if you rejoin the world, chunk with cable-joint desappears and became void. No power source is required to reproduce this issue. 
There is log file:
[daemon-16060.out.log](https://github.com/rikka0w0/SimElectricity/files/15179281/daemon-16060.out.log)

**Comment by AuroraRAS** [comment]
Our game mods have just undergone a major overhaul; please upgrade to the latest version.
