### ISSUE TITLE
crash on removing tower block

### ISSUE THREAD

**Issue by l89669** [RoyalAliceAcademyOfSciences/SimElectricity#9]
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 17-3-13 下午11:12
Description: Ticking memory connection

java.util.NoSuchElementException
	at java.util.LinkedList$ListItr.next(Unknown Source)
	at simElectricity.Common.EnergyNet.SEGraph.removeGridVertex(SEGraph.java:127)
	at simElectricity.Common.EnergyNet.EnergyNetDataProvider.removeGridNode(EnergyNetDataProvider.java:69)
	at simElectricity.Common.EnergyNet.EnergyNet.removeGridNode(EnergyNet.java:262)
	at simElectricity.Common.EnergyNet.EnergyNetEventHandler.onGridObjectDetach(EnergyNetEventHandler.java:170)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_112_EnergyNetEventHandler_onGridObjectDetach_GridObjectDetachEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at simElectricity.Common.EnergyNet.EnergyNetAgent.detachGridObject(EnergyNetAgent.java:155)
	at simElectricity.Templates.Blocks.BlockTower.func_149749_a(BlockTower.java:95)
	at net.minecraft.world.chunk.Chunk.func_150807_a(Chunk.java:600)
	at net.minecraft.world.World.func_147465_d(World.java:451)
	at net.minecraft.world.World.func_147468_f(World.java:573)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1341)
	at net.minecraft.block.Block.removedByPlayer(Block.java:1335)
	at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:247)
	at net.minecraft.server.management.ItemInWorldManager.func_73079_d(ItemInWorldManager.java:240)
	at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:278)
	at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:151)
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:489)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

mc forge 1.7.10-1614, forge client
creative mode, happend when removing a tower block which has a HV wire attached.

**Comment by rikka0w0** [comment]
hi we have investigated the problem, but we failed to recreate the error. have you used any previous versions? the data structure has changed many times. if you use the latest version to load a map which is created by a ealier version, it is likely to have this kind of problems.
before the formal release of beta version, we can not guarantee backward compatibility.
if you have any problems/concerns, dont feel hesitate to contact us!

**Comment by rikka0w0** [comment]
This bug has been fixed in the latest update!

**Comment by l89669** [comment]
Confirmed it has been fixed, thanks!

**Comment by l89669** [comment]
[Suggestion] Seriously, if you guys can make the template mod more interesting and powerful, maybe there will be more and more modders using your API, just like CofhCore and Thermal Expansion.
